### ISSUE TITLE
Collection, reduction and similar actions fail in serialization

### ISSUE THREAD

**Issue by zaytsevpavel** [almond-sh/almond#105]
Hi, I have scala-2.11 and Spark-2.0.0
My spark cluster configuration works perfectly with Python API - Pyspark
I decided to use jupyter-scala as I prefer to use Spark with Scala.
This is how I set up deps:
```
classpath.add("org.apache.spark" % "spark-core_2.11" % "2.0.0")
classpath.add("org.apache.hadoop" % "hadoop-client" % "2.7.3")
```

This is how i setup spark context:
```
val sparkConf = new SparkConf()
  .setAppName("preprocessing")
  .setMaster("spark://HadoopMaster:7077")
  .set("spark.executor.memory", "2g")
  .set("spark.driver.memory", "2g")
val sc = new SparkContext(sparkConf)
```

Gives a good output:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hduser/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hduser/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/tika/tika-app/1.13/tika-app-1.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
INFO  Running Spark version 2.0.0
WARN  Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
INFO  Changing view acls to: hduser
INFO  Changing modify acls to: hduser
INFO  Changing view acls groups to: 
INFO  Changing modify acls groups to: 
INFO  SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(hduser); groups with view permissions: Set(); users  with modify permissions: Set(hduser); groups with modify permissions: Set()
INFO  Successfully started service 'sparkDriver' on port 34812.
INFO  Registering MapOutputTracker
INFO  Registering BlockManagerMaster
INFO  Created local directory at /tmp/blockmgr-ebe8f547-9069-415e-8ccf-17aea7444e63
INFO  MemoryStore started with capacity 366.3 MB
INFO  Registering OutputCommitCoordinator
INFO  Logging initialized @52645ms
INFO  jetty-9.2.z-SNAPSHOT
INFO  Started o.s.j.s.ServletContextHandler@7c1892b3{/jobs,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@774585cc{/jobs/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@7d2ba1aa{/jobs/job,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@3812c795{/jobs/job/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@27472e{/stages,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@5b17d903{/stages/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@7b91153a{/stages/stage,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@55115bb2{/stages/stage/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@6fb56809{/stages/pool,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@a0f7b3d{/stages/pool/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@79c48783{/storage,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@26579fc2{/storage/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@62665e21{/storage/rdd,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@13c117c3{/storage/rdd/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@4ee472a7{/environment,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@54574d36{/environment/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@49096cb{/executors,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@1ff4f695{/executors/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@7268de86{/executors/threadDump,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@1c381300{/executors/threadDump/json,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@1c1ef882{/static,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@2466e5ca{/,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@10ce932e{/api,null,AVAILABLE}
INFO  Started o.s.j.s.ServletContextHandler@4cb22224{/stages/stage/kill,null,AVAILABLE}
INFO  Started ServerConnector@30c191e6{HTTP/1.1}{0.0.0.0:4040}
INFO  Started @52897ms
INFO  Successfully started service 'SparkUI' on port 4040.
INFO  Bound SparkUI to 0.0.0.0, and started at http://198.199.104.160:4040
INFO  Connecting to master spark://HadoopMaster:7077...
INFO  Successfully created connection to HadoopMaster/192.241.208.96:7077 after 23 ms (0 ms spent in bootstraps)
INFO  Connected to Spark cluster with app ID app-20160925091147-0000
INFO  Executor added: app-20160925091147-0000/0 on worker-20160925090534-104.236.189.66-40669 (104.236.189.66:40669) with 6 cores
INFO  Granted executor ID app-20160925091147-0000/0 on hostPort 104.236.189.66:40669 with 6 cores, 2.0 GB RAM
INFO  Executor added: app-20160925091147-0000/1 on worker-20160925090534-104.236.190.18-37709 (104.236.190.18:37709) with 6 cores
INFO  Granted executor ID app-20160925091147-0000/1 on hostPort 104.236.190.18:37709 with 6 cores, 2.0 GB RAM
INFO  Executor added: app-20160925091147-0000/2 on worker-20160925090534-104.236.189.10-37184 (104.236.189.10:37184) with 6 cores
INFO  Granted executor ID app-20160925091147-0000/2 on hostPort 104.236.189.10:37184 with 6 cores, 2.0 GB RAM
INFO  Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33788.
INFO  Server created on 198.199.104.160:33788
INFO  Registering BlockManager BlockManagerId(driver, 198.199.104.160, 33788)
INFO  Registering block manager 198.199.104.160:33788 with 366.3 MB RAM, BlockManagerId(driver, 198.199.104.160, 33788)
INFO  Registered BlockManager BlockManagerId(driver, 198.199.104.160, 33788)
INFO  Executor updated: app-20160925091147-0000/2 is now RUNNING
INFO  Executor updated: app-20160925091147-0000/1 is now RUNNING
INFO  Executor updated: app-20160925091147-0000/0 is now RUNNING
INFO  Started o.s.j.s.ServletContextHandler@43086ef3{/metrics/json,null,AVAILABLE}
INFO  SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
```

When I get data no problem too:
```
val test_path = "hdfs://HadoopMaster:9000/data/ag/*/*"
val pp = sc.textFile(test_path)
```

```
test_path: String = "hdfs://HadoopMaster:9000/data/ag/*/*"
pp: org.apache.spark.rdd.RDD[String] = hdfs://HadoopMaster:9000/data/ag/*/* MapPartitionsRDD[28] at textFile at Main.scala:32
```

```
val data = Array(1, 2, 3, 4, 5)
val distData = sc.parallelize(data)
```

```
data: Array[Int] = Array(1, 2, 3, 4, 5)
distData: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at Main.scala:28
```

However, when I try to collect after mapping:
```
sc.parallelize(1 to 10).map(x => x + x).collect()
```

Gives this error?
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 10 in stage 2.0 failed 4 times, most recent failure: Lost task 10.3 in stage 2.0 (TID 157, 104.236.190.18): java.lang.ClassNotFoundException: cmd6$$user$$anonfun$1$$anonfun$apply$1
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
    at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:85)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace: (Job aborted due to stage failure: Task 10 in stage 2.0 failed 4 times, most recent failure: Lost task 10.3 in stage 2.0 (TID 157, 104.236.190.18): java.lang.ClassNotFoundException: cmd6$$user$$anonfun$1$$anonfun$apply$1
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
    at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
    at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:85)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:)
  org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
  scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  scala.Option.foreach(Option.scala:257)
  org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
  org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1911)
  org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:893)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  org.apache.spark.rdd.RDD.collect(RDD.scala:892)
  cmd6$$user$$anonfun$1.apply(Main.scala:25)
  cmd6$$user$$anonfun$1.apply(Main.scala:24)
java.lang.ClassNotFoundException: cmd6$$user$$anonfun$1$$anonfun$apply$1 (cmd6$$user$$anonfun$1$$anonfun$apply$1)
  java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  java.lang.Class.forName0(Native Method)
  java.lang.Class.forName(Class.java:348)
  org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
  java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
  java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
  org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
  org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
  org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
  org.apache.spark.scheduler.Task.run(Task.scala:85)
  org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
```

What might be the issue?

**Comment by alexarchambault** [comment]
Closing this issue, as it's about a rather old Almond version now
