### ISSUE TITLE
Lots of output messages cause kernel to stuck

### ISSUE THREAD

**Issue by vsevolodstep-db** [almond-sh/almond#1061]
## Bug Description

When I run this code
```
for (i <- 1 to 1000000) {
    println(i)
}
```
the kernel prints first several hundreds of messages, then gets stuck. These are the last messages from kernel log:
```
DEBUG ZeromqSocketImpl Sending:
  header: {"msg_id":"bce7adb0-680b-42d4-a94c-3fc48ba3944e","username":"","session":"906423a7-eff7-4c4a-90df-faff1fd46c01","msg_type":"stream","version":"5.2"}
  content: {"name":"stdout","text":"994"}
  idents: List(stdout)
DEBUG ZeromqSocketImpl Sending:
  header: {"msg_id":"bceddeab-3162-4bb1-bc5d-56419ea269db","username":"","session":"906423a7-eff7-4c4a-90df-faff1fd46c01","msg_type":"stream","version":"5.2"}
  content: {"name":"stdout","text":"\n"}
  idents: List(stdout)
```

There are two relevant kernel threads. The first one is interpreter thread, which is stuck on trying to push message to ZMQ connection:
```
"scala-interpreter-1" #26 daemon prio=5 os_prio=31 cpu=918.35ms elapsed=77.41s tid=0x0000000123999800 nid=0x7e03 waiting on condition  [0x0000000174faa000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x00000003fdfd9e50> (a cats.effect.internals.IOPlatform$OneShotLatch)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.12/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.12/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.12/AbstractQueuedSynchronizer.java:1039)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.12/AbstractQueuedSynchronizer.java:1345)
	at cats.effect.internals.IOPlatform$.$anonfun$unsafeResync$2(IOPlatform.scala:52)
	at cats.effect.internals.IOPlatform$$$Lambda$302/0x0000000800367040.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.package$.blocking(package.scala:146)
	at cats.effect.internals.IOPlatform$.unsafeResync(IOPlatform.scala:52)
	at cats.effect.IO.unsafeRunTimed(IO.scala:342)
	at cats.effect.IO.unsafeRunSync(IO.scala:256)
	at almond.interpreter.messagehandlers.InterpreterMessageHandlers$QueueOutputHandler.print(InterpreterMessageHandlers.scala:229)
	at almond.interpreter.messagehandlers.InterpreterMessageHandlers$QueueOutputHandler.stdout(InterpreterMessageHandlers.scala:233)
	at almond.Execute.$anonfun$capturingOutput$1(Execute.scala:167)
	at almond.Execute.$anonfun$capturingOutput$1$adapted(Execute.scala:167)
	at almond.Execute$$Lambda$1233/0x00000008008c5840.apply(Unknown Source)
	at almond.internals.CaptureImpl.$anonfun$out$1(CaptureImpl.scala:22)
	at almond.internals.CaptureImpl.$anonfun$out$1$adapted(CaptureImpl.scala:22)
	at almond.internals.CaptureImpl$$Lambda$156/0x0000000800225840.apply(Unknown Source)
	at almond.internals.FunctionOutputStream.flush(FunctionOutputStream.scala:71)
	at java.io.PrintStream.write(java.base@11.0.12/PrintStream.java:561)
	- locked <0x00000003c0d10250> (a java.io.PrintStream)
	at sun.nio.cs.StreamEncoder.writeBytes(java.base@11.0.12/StreamEncoder.java:233)
	at sun.nio.cs.StreamEncoder.implFlushBuffer(java.base@11.0.12/StreamEncoder.java:312)
	at sun.nio.cs.StreamEncoder.flushBuffer(java.base@11.0.12/StreamEncoder.java:104)
	- locked <0x00000003c0d102a8> (a java.io.OutputStreamWriter)
	at java.io.OutputStreamWriter.flushBuffer(java.base@11.0.12/OutputStreamWriter.java:181)
	at java.io.PrintStream.newLine(java.base@11.0.12/PrintStream.java:625)
	- locked <0x00000003c0d10250> (a java.io.PrintStream)
	at java.io.PrintStream.println(java.base@11.0.12/PrintStream.java:900)
	- locked <0x00000003c0d10250> (a java.io.PrintStream)
	at scala.Console$.println(Console.scala:271)
	at scala.Predef$.println(Predef.scala:404)
	at ammonite.$sess.cmd0$Helper.$anonfun$res0$1(cmd0.sc:2)
	at ammonite.$sess.cmd0$Helper$$Lambda$2041/0x0000000800b90840.apply$mcVI$sp(Unknown Source)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at ammonite.$sess.cmd0$Helper.<init>(cmd0.sc:1)
	at ammonite.$sess.cmd0$.<init>(cmd0.sc:7)
	at ammonite.$sess.cmd0$.<clinit>(cmd0.sc)
	at ammonite.$sess.cmd0.$main(cmd0.sc)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.12/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.12/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.12/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.12/Method.java:566)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$evalMain$1(Evaluator.scala:108)
	at ammonite.runtime.Evaluator$$anon$1$$Lambda$2040/0x0000000800b8fc40.apply(Unknown Source)
	at ammonite.util.Util$.withContextClassloader(Util.scala:24)
	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:90)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$2(Evaluator.scala:127)
	at ammonite.runtime.Evaluator$$anon$1$$Lambda$2039/0x0000000800b8f040.apply(Unknown Source)
	at ammonite.util.Catching.map(Res.scala:117)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$1(Evaluator.scala:121)
	at ammonite.runtime.Evaluator$$anon$1$$Lambda$2038/0x0000000800b8d840.apply(Unknown Source)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.runtime.Evaluator$$anon$1.processLine(Evaluator.scala:120)
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$5(Interpreter.scala:307)
	at ammonite.interp.Interpreter$$Lambda$2029/0x0000000800b79840.apply(Unknown Source)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$2(Interpreter.scala:290)
	at ammonite.interp.Interpreter$$Lambda$1302/0x000000080090c040.apply(Unknown Source)
	at ammonite.util.Catching.flatMap(Res.scala:115)
	at ammonite.interp.Interpreter.evaluateLine(Interpreter.scala:289)
	- locked <0x00000003c0d14518> (a almond.amm.AmmInterpreter$$anon$1)
	at ammonite.interp.Interpreter.$anonfun$processLine$6(Interpreter.scala:277)
	at ammonite.interp.Interpreter$$Lambda$1301/0x000000080090b840.apply(Unknown Source)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processLine$4(Interpreter.scala:260)
	at ammonite.interp.Interpreter$$Lambda$1251/0x00000008008d2040.apply(Unknown Source)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at ammonite.interp.Interpreter.$anonfun$processLine$2(Interpreter.scala:253)
	at ammonite.interp.Interpreter$$Lambda$1244/0x00000008008cc040.apply(Unknown Source)
	at ammonite.util.Catching.flatMap(Res.scala:115)
	at ammonite.interp.Interpreter.processLine(Interpreter.scala:252)
	- locked <0x00000003c0d14518> (a almond.amm.AmmInterpreter$$anon$1)
	at almond.Execute.$anonfun$ammResult$7(Execute.scala:262)
	at almond.Execute$$Lambda$1232/0x00000008008c4c40.apply(Unknown Source)
	at almond.internals.CaptureImpl.$anonfun$apply$2(CaptureImpl.scala:53)
	at almond.internals.CaptureImpl$$Lambda$1236/0x00000008008c6c40.apply(Unknown Source)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at almond.internals.CaptureImpl.$anonfun$apply$1(CaptureImpl.scala:45)
	at almond.internals.CaptureImpl$$Lambda$1235/0x00000008008c6840.apply(Unknown Source)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at almond.internals.CaptureImpl.apply(CaptureImpl.scala:45)
	at almond.Execute.capturingOutput(Execute.scala:167)
	at almond.Execute.$anonfun$ammResult$6(Execute.scala:249)
	at almond.Execute$$Lambda$1230/0x00000008008c4440.apply(Unknown Source)
	at almond.Execute.$anonfun$withClientStdin$1(Execute.scala:147)
	at almond.Execute$$Lambda$1231/0x00000008008c4840.apply(Unknown Source)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at almond.Execute.withClientStdin(Execute.scala:143)
	at almond.Execute.$anonfun$ammResult$5(Execute.scala:249)
	at almond.Execute$$Lambda$1229/0x00000008008c4040.apply(Unknown Source)
	at almond.Execute.withInputManager(Execute.scala:135)
	at almond.Execute.$anonfun$ammResult$4(Execute.scala:248)
	at almond.Execute$$Lambda$1226/0x00000008008c2c40.apply(Unknown Source)
	at ammonite.repl.Signaller.apply(Signaller.scala:28)
	at almond.Execute.interruptible(Execute.scala:190)
	at almond.Execute.$anonfun$ammResult$3(Execute.scala:247)
	at almond.Execute$$Lambda$1225/0x00000008008c2040.apply(Unknown Source)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at almond.Execute.$anonfun$ammResult$1(Execute.scala:234)
	at almond.Execute$$Lambda$1122/0x0000000800887c40.apply(Unknown Source)
	at almond.Execute.withOutputHandler(Execute.scala:158)
	at almond.Execute.ammResult(Execute.scala:225)
	at almond.Execute.apply(Execute.scala:335)
	at almond.ScalaInterpreter.execute(ScalaInterpreter.scala:130)
	at almond.interpreter.InterpreterToIOInterpreter.$anonfun$execute$2(InterpreterToIOInterpreter.scala:69)
	at almond.interpreter.InterpreterToIOInterpreter$$Lambda$1118/0x000000080086e840.apply(Unknown Source)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:108)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:480)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:501)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:439)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
```

And the second one is responsible for actually pushing the message through the socket and it's also stuck:

```
"scala-kernel-zeromq-Publish-1" #22 daemon prio=5 os_prio=31 cpu=65340.67ms elapsed=77.68s tid=0x0000000123941000 nid=0x7403 runnable  [0x0000000174366000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.read0(java.base@11.0.12/Native Method)
	at sun.nio.ch.FileDispatcherImpl.read(java.base@11.0.12/FileDispatcherImpl.java:48)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(java.base@11.0.12/IOUtil.java:276)
	at sun.nio.ch.IOUtil.read(java.base@11.0.12/IOUtil.java:245)
	at sun.nio.ch.IOUtil.read(java.base@11.0.12/IOUtil.java:223)
	at sun.nio.ch.SourceChannelImpl.read(java.base@11.0.12/SourceChannelImpl.java:256)
	at zmq.Signaler.recv(Signaler.java:165)
	at zmq.Mailbox.recv(Mailbox.java:97)
	at zmq.SocketBase.processCommands(SocketBase.java:937)
	at zmq.SocketBase.send(SocketBase.java:702)
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:3205)
	at almond.channels.zeromq.ZeromqSocketImpl.$anonfun$send$7(ZeromqSocketImpl.scala:118)
	at almond.channels.zeromq.ZeromqSocketImpl.$anonfun$send$7$adapted(ZeromqSocketImpl.scala:117)
	at almond.channels.zeromq.ZeromqSocketImpl$$Lambda$732/0x0000000800685040.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at almond.channels.zeromq.ZeromqSocketImpl.$anonfun$send$2(ZeromqSocketImpl.scala:117)
	at almond.channels.zeromq.ZeromqSocketImpl$$Lambda$724/0x0000000800683040.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:108)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:480)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:501)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:439)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)
```

**When I run the same code in IPython, it works and prints all numbers**

## Possible cause
The key difference of IPython kernel from Almond.sh is that it **buffers** its stdout/stderr messages for a short period of time. If I run the sample code in Almond.sh, each `println` statement produces two IOPub messages: one for the number, and another one for the newline character `\n`. When I run the same code in IPython, it generates only one (or a couple) of messages.

Spawning lots of ZMQ messages is probably the cause why the socket becomes blocked. ZMQ has a concept of [high water mark](http://api.zeromq.org/3-2:zmq-setsockopt): the maximal number of messages that may be queued on socket. If the queue is full, either new messages are dropped or the socket becomes blocked. The default value for HWM is 1000.

I tried to change that value by calling `channel.setHWM(???)` in `ZeromqSocketImpl`. I confirmed that the larger the number is, the more numbers I'm able to print without getting stuck. Moreover, setting this number to 0 (effectively disabling queue size constraint) prints all messages!

It's still not entirely clear to me why the threads responsible for message sending become blocked, but the root cause is definitely related to a high rate of ZMQ messages.

## Possible solution
Ideally, implement some buffering for output messages similar to IPython does. 
Alternatively, set socket HWM to 0, but I'm not quite sure what implications that might cause.

**Comment by vsevolodstep-db** [comment]
Closing this issue as the workaround was merged
