### ISSUE TITLE
Scala 2.13.8 Almond 0.13.14 issue

### ISSUE THREAD

**Issue by rehanann** [almond-sh/almond#1154]
```
Jupyter pip
jupyter_client             8.2.0
jupyter_core               5.3.0
jupyter-events             0.6.3
jupyter-lsp                2.2.0
jupyter_server             2.6.0
jupyter_server_terminals   0.4.4
jupyterlab                 4.0.2
jupyterlab-pygments        0.2.2
jupyterlab_server          2.23.0

Scala  2.13.8
Almond 0.13.14

Kernel.conf
{
  "argv": [
    "spark-submit", "--class", "coursier.bootstrap.launcher.Launcher", "/opt/spark/work-dir/.local/share/jupyter/kernels/scala/launcher.jar",
    "--extra-repository", "https://xxx/artifactory/maven",
    "--connection-file",
    "{connection_file}"
  ],
  "display_name": "Scala",
  "language": "scala"
} 

------------ UNHANDLED EXCEPTION ---------- (scala-kernel-zeromq-Publish-1)
java.lang.NoSuchMethodError: 'scala.collection.immutable.IndexedSeq cats.kernel.instances.StaticMethods$.wrapMutableIndexedSeq(scala.collection.mutable.IndexedSeq)'
	at cats.data.ChainInstances$$anon$3.traverse(Chain.scala:1039)
	at cats.data.ChainInstances$$anon$3.traverse(Chain.scala:1000)
	at fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:243)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:196)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:480)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:491)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.ForwardCancelable.loop$1(ForwardCancelable.scala:46)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1(ForwardCancelable.scala:52)
	at cats.effect.internals.ForwardCancelable.$anonfun$cancel$1$adapted(ForwardCancelable.scala:52)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:464)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:165)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:38)
	at cats.effect.IO.unsafeRunAsync(IO.scala:274)
	at cats.effect.internals.IORace$.onSuccess$1(IORace.scala:39)
	at cats.effect.internals.IORace$.$anonfun$simple$5(IORace.scala:82)
	at cats.effect.internals.IORace$.$anonfun$simple$5$adapted(IORace.scala:80)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:192)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:480)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:501)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:439)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[I 2023-06-14 17:01:14.822 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
```

**Comment by alexarchambault** [comment]
Closing as stale / needing details
