### ISSUE TITLE
ammonite is throwing an IvyResolutionException when I launch Jupyter

### ISSUE THREAD

**Issue by joao-parana** [almond-sh/almond#119]
Why ammonite is throwing an IvyResolutionException ?

I launch Jupyter this way:

```bash
jupyter notebook --no-browser --ip spark.local
```

**Console output: **

```
[I 20:16:41.896 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 20:16:41.902 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 20:16:42.180 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 20:16:42.180 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named nbbrowserpdf.exporters.pdf
[I 20:16:42.189 NotebookApp] [nb_conda] enabled
[I 20:16:42.788 NotebookApp] [nb_anacondacloud] enabled
[I 20:16:42.798 NotebookApp] Serving notebooks from local directory: /desenv/java
[I 20:16:42.799 NotebookApp] 0 active kernels 
[I 20:16:42.799 NotebookApp] The Jupyter Notebook is running at: http://spark.local:8888/
[I 20:16:42.800 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 20:18:02.202 NotebookApp] 302 GET / (172.17.0.1) 0.94ms
[I 20:18:50.537 NotebookApp] Creating new notebook in 
[I 20:18:50.553 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[I 20:18:51.425 NotebookApp] Kernel started: cf1b75cf-01f6-40c6-9c66-03c29562f9a0
[W 20:19:01.641 NotebookApp] Timeout waiting for kernel_info reply from cf1b75cf-01f6-40c6-9c66-03c29562f9a0
```

When I click on scala option in the Jupyter Web Page I see this.

```
Exception in thread "main" java.lang.RuntimeException: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  file:/root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar: not found: /root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
	at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
	at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:381)
	. . . 
```

**Caused by:**

```
Caused by: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  file:/root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar: not found: /root/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
	at ammonite.runtime.tools.DependencyThing.resolveArtifact(DependencyThing.scala:106)
	at ammonite.runtime.Interpreter.loadIvy(Interpreter.scala:630)
	at ammonite.runtime.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:655)
	at jupyter.scala.Interp.<init>(Interp.scala:75)
	. . . 
```

**Comment by nightscape** [comment]
@joao-parana did you find a solution to this already?
@alexarchambault do you have a clue what this is about?

**Comment by nightscape** [comment]
Ok, simple workaround (copying the file) works:
```
mkdir -p ~/.m2/repository/org/scala-lang/scala-reflect/2.11.8/
cp ~/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar ~/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
```
It would still be interesting why the artifact isn't downloaded automatically if it is required.

**Comment by alexarchambault** [comment]
Should be fine with the current master, and releases under the "almond" name. (`~/.m2` isn't added as a repository by default anymore.)
