### ISSUE TITLE
org.apache.spark.SparkException: Yarn application has already ended!

### ISSUE THREAD

**Issue by fdas3213** [almond-sh/almond#159]
I am using scala jupyter notebook for spark, and when I tried to configure spark at first by:

```
import $exclude.`org.slf4j:slf4j-log4j12`, $ivy.`org.slf4j:slf4j-nop:1.7.21` // for cleaner logs
import $profile.`hadoop-2.6`
import $ivy.`org.apache.spark::spark-sql:2.1.0` // adjust spark version - spark >= 2.0
import $ivy.`org.jupyter-scala::spark:0.4.2` // for JupyterSparkSession (SparkSession aware of the jupyter-scala kernel)

import org.apache.spark._
import org.apache.spark.sql._
import jupyter.spark.session._

val spark: SparkSession = JupyterSparkSession.builder().jupyter().yarn("/etc/hadoop/conf").master("yarn-client").appName("notebook").getOrCreate()
val sc = spark.sparkContext
```

I got the following error:
```
org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.
  org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:85)
  org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:62)
  org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:156)
  org.apache.spark.SparkContext.<init>(SparkContext.scala:509)
  org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2313)
  org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:868)
  org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:860)
  scala.Option.getOrElse(Option.scala:121)
  org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:860)
  jupyter.spark.session.JupyterSparkSession$Builder.getOrCreate(JupyterSparkSession.scala:48)
  $sess.cmd1Wrapper$Helper.<init>(cmd1.sc:10)
  $sess.cmd1Wrapper.<init>(cmd1.sc:116)
  $sess.cmd1$.<init>(cmd1.sc:60)
  $sess.cmd1$.<clinit>(cmd1.sc:-1)
```
Could anyone tell me what might be going wrong here? Thank you so much!

**Comment by kentore82** [comment]
I get the same. For me its a Spark/Yarn classpath issue. Looking at the container logs gives me
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/esotericsoftware/kryo/io/Output
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:230)
	at org.apache.spark.SparkEnv$.instantiateClass$1(SparkEnv.scala:261)
	at org.apache.spark.SparkEnv$.instantiateClassFromConf$1(SparkEnv.scala:282)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:285)
	at org.apache.spark.SparkEnv$.createExecutorEnv(SparkEnv.scala:201)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$$anonfun$run$1.apply$mcV$sp(CoarseGrainedExecutorBackend.scala:223)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:67)
	at org.apache.spark.deploy.SparkHadoopUtil$$anon$2.run(SparkHadoopUtil.scala:66)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1692)
	at org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:66)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.run(CoarseGrainedExecutorBackend.scala:188)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:284)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
```
`com.esotericsoftware.kryo.io.Output` is shipped to Sparks classpath with `kryo-shaded-3.0.3.jar` so it should be there...

**Comment by ixaxaar** [comment]
+1 DId this on a fresh EMR cluster:

```bash
wget https://raw.githubusercontent.com/alexarchambault/jupyter-scala/master/jupyter-scala
chmod +x ./jupyter-scala
./jupyter-scala
```

And in notebook:

```scala
import $exclude.`org.slf4j:slf4j-log4j12`, $ivy.`org.slf4j:slf4j-nop:1.7.21` // for cleaner logs
import $profile.`hadoop-2.6`
import $ivy.`org.apache.spark::spark-sql:2.3.0` // adjust spark version - spark >= 2.0
import $ivy.`org.apache.hadoop:hadoop-aws:2.8.3`
import $ivy.`org.jupyter-scala::spark:0.4.2` // for JupyterSparkSession (SparkSession aware of the jupyter-scala kernel)

import org.apache.spark._
import org.apache.spark.sql._
import jupyter.spark.session._

val sparkSession = JupyterSparkSession.builder() // important - call this rather than SparkSession.builder()
  .jupyter() // this method must be called straightaway after builder()
  .yarn("/etc/hadoop/conf/") // optional, for Spark on YARN - argument is the Hadoop conf directory
  .emr("5.15.0") // on AWS ElasticMapReduce, this adds aws-related to the spark jar list
  .master("yarn-client") // change to "yarn-client" on YARN
  .appName("scala_test0r")
  .getOrCreate()
```

which results in:

```scala
org.apache.spark.SparkException: Yarn application has already ended! It might have been killed or unable to launch application master.
  org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.waitForApplication(YarnClientSchedulerBackend.scala:89)
  org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:63)
  org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:164)
  org.apache.spark.SparkContext.<init>(SparkContext.scala:500)
  org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2486)
  org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:930)
  org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:921)
  scala.Option.getOrElse(Option.scala:121)
  org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
  jupyter.spark.session.JupyterSparkSession$Builder.getOrCreate(JupyterSparkSession.scala:48)
  $sess.cmd5Wrapper$Helper.<init>(cmd5.sc:7)
  $sess.cmd5Wrapper.<init>(cmd5.sc:201)
  $sess.cmd5$.<init>(cmd5.sc:186)
  $sess.cmd5$.<clinit>(cmd5.sc:-1)
```

**Comment by alexarchambault** [comment]
Closing as this is, versions of most things involved have much newer versions now
