### ISSUE TITLE
kernel keeps restarting (failing to resolve dependencies)

### ISSUE THREAD

**Issue by szeitlin** [almond-sh/almond#172]
Able to launch notebook and create one, but can't type anything in it or have it running for more than a couple of seconds. Logs indicate that it's not finding dependencies. I followed the instructions on the README. Maybe a good idea to list what dependencies are needed, and where they should be installed (I'm on a Mac running 10.12.6, jupyter version 5.1 with python 3.6). 

```
Downloading https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom.sha1
Downloading https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom
Downloading https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/maven-metadata.xml.sha1
Downloading https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom.sha1
Downloading https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom
Downloading https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/maven-metadata.xml
Downloading https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/maven-metadata.xml.sha1
Exception in thread "main" java.lang.RuntimeException: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  Dependency(org.jupyter-scala:scala-api_2.11.11,0.4.3-SNAPSHOT,compile,Set(),Attributes(,),false,true): not found: /Users/szeitlin/.ivy2/local/org.jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/ivys/ivy.xml, not found: https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom, not found: https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:174)
	at jupyter.scala.JupyterScalaApp.delayedEndpoint$jupyter$scala$JupyterScalaApp$1(JupyterScala.scala:93)
	at jupyter.scala.JupyterScalaApp$delayedInit$body.apply(JupyterScala.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
	at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at caseapp.App$class.apply(App.scala:46)
	at jupyter.scala.JupyterScalaApp.apply(JupyterScala.scala:13)
	at caseapp.AppOf.main(App.scala:121)
	at jupyter.scala.JupyterScala.main(JupyterScala.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.cli.qJ.a(Unknown Source)
	at coursier.cli.qI.j(Unknown Source)
	at coursier.cli.qO.a(Unknown Source)
	at d.g.a.c(Unknown Source)
	at b.b.d_(Unknown Source)
	at d.b.d.E.g(Unknown Source)
	at d.b.e.aU.g(Unknown Source)
	at a.c.a(Unknown Source)
	at coursier.cli.qI.b(Unknown Source)
	at coursier.cli.O.b(Unknown Source)
	at b.I.d_(Unknown Source)
	at d.E.h(Unknown Source)
	at a.aH.a(Unknown Source)
	at coursier.cli.Coursier.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.Bootstrap.main(Bootstrap.java:412)
Caused by: ammonite.runtime.tools.DependencyThing$IvyResolutionException: failed to resolve dependencies:
  Dependency(org.jupyter-scala:scala-api_2.11.11,0.4.3-SNAPSHOT,compile,Set(),Attributes(,),false,true): not found: /Users/szeitlin/.ivy2/local/org.jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/ivys/ivy.xml, not found: https://repo1.maven.org/maven2/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom, not found: https://oss.sonatype.org/content/repositories/releases/org/jupyter-scala/scala-api_2.11.11/0.4.3-SNAPSHOT/scala-api_2.11.11-0.4.3-SNAPSHOT.pom
	at ammonite.runtime.tools.DependencyThing.resolveArtifact(DependencyThing.scala:90)
	at ammonite.interp.Interpreter.loadIvy(Interpreter.scala:658)
	at ammonite.interp.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:853)
	at jupyter.scala.Interp.<init>(Interp.scala:92)
	at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:98)
	at jupyter.scala.JupyterScalaApp$$anon$5.apply(JupyterScala.scala:97)
	at jupyter.kernel.server.Server$.launch(Server.scala:80)
	at jupyter.kernel.server.Server$.apply(Server.scala:123)
	at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
	at jupyter.kernel.server.ServerApp$$anonfun$4.apply(ServerApp.scala:171)
	at scala.util.Try$.apply(Try.scala:192)
	at jupyter.kernel.server.ServerApp$.apply(ServerApp.scala:171)
	... 36 more
```

**Comment by ckchow** [comment]
Looks like you modified your install script to pull 0.4.3-SNAPSHOT instead of the mainline 0.4.2 release? Was this intentional? I think if you have the version modified like that, the intent is that you are going to install a custom kernel built on your own machine that you used publishLocal to make.

**Comment by szeitlin** [comment]
just trying to figure out how this is intended to be used. I think I started with the 0.4.2 version and that didn't work, either. I gave up because the instructions weren't clear.

**Comment by frgomes** [comment]
You may try my installation script for Debian.
I suppose you would have to hammer the ``apt-get`` thing, at least.

No idea whatsoever if my script would make any difference in your scenario.
However, I've never found problems ("it works for me") and maybe it could help you somehow.
https://gist.github.com/frgomes/24c1923f2c9f14a27b14

**Comment by alexarchambault** [comment]
Closing, the current master, and releases under the "almond" name, don't run resolutions upon startup anymore.
