### ISSUE TITLE
coursier error while evaluating import

### ISSUE THREAD

**Issue by aappddeevv** [almond-sh/almond#260]
I installed the latest ammonite, coursier and almond. However when I do the following imports (or any import) I get an error. Is this a configuration / version skew issue? Evaluating `1+1` works fine and amm works fine for the same imports from the command line so it seems to be almond related. 

Thoughts?

```scala
import $ivy.`org.typelevel::cats-core:1.4.0`
import $ivy.`org.typelevel::cats-effect:1.0.0`
```
I get
```sh
java.lang.NoSuchMethodError: coursier.CachePath.localFile(Ljava/lang/String;Ljava/io/File;Ljava/lang/String;Z)Ljava/io/File;
	at coursier.Cache$.localFile(Cache.scala:41)
	at coursier.Cache$.$anonfun$download$63(Cache.scala:797)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at coursier.Cache$.download(Cache.scala:796)
	at coursier.Cache$.file(Cache.scala:953)
	at coursier.Cache$.$anonfun$fetch$1(Cache.scala:1031)
	at coursier.maven.MavenRepository.findVersioning(MavenRepository.scala:368)
	at coursier.maven.MavenRepository.findNoInterval(MavenRepository.scala:277)
	at coursier.maven.MavenRepository.find(MavenRepository.scala:438)
	at coursier.Fetch$.$anonfun$find$1(Fetch.scala:38)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.immutable.List.map(List.scala:294)
	at coursier.Fetch$.find(Fetch.scala:38)
	at coursier.Fetch$.get$1(Fetch.scala:67)
	at coursier.Fetch$.$anonfun$from$2(Fetch.scala:68)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.collection.IterableLike.foreach(IterableLike.scala:70)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at coursier.Fetch$.$anonfun$from$1(Fetch.scala:65)
	at coursier.core.ResolutionProcess$.$anonfun$fetchAll$10(ResolutionProcess.scala:197)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:10)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by newca12** [comment]
FWIW almond v0.2.0 fix this issue for me

**Comment by aappddeevv** [comment]
I've confirmed that updating everything seems to have fixed the import issue. Thanks!

**Comment by aappddeevv** [comment]
Note that the latest when I tested the recommendation was 0.2.1.
