### ISSUE TITLE
Build error while using sbt - unknown option 'merged'

### ISSUE THREAD

**Issue by david-freistrom** [almond-sh/almond#339]
Hi,
while using the current master branch, after clone and just run sbt ./build.sbt runs into an error.

SBT-Version: 1.2.8
Java-Version: OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
OS-Version: CentOS 7 Minimal
Kernel: 2.6.32-openvz-042stab127.2-amd64

```
[info] Loading settings for project almond from build.sbt ...
error: unknown option `merged'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>] 
		[<pattern>...]
   or: git tag -v <tagname>...
    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags
Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns
Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object
error: unknown option `merged'
usage: git tag [-a|-s|-u <key-id>] [-f] [-m <msg>|-F <file>] <tagname> [<head>]
   or: git tag -d <tagname>...
   or: git tag -l [-n[<num>]] [--contains <commit>] [--points-at <object>] 
		[<pattern>...]
   or: git tag -v <tagname>...
    -l, --list            list tag names
    -n[<n>]               print <n> lines of each tag message
    -d, --delete          delete tags
    -v, --verify          verify tags
Tag creation options
    -a, --annotate        annotated tag, needs a message
    -m, --message <message>
                          tag message
    -F, --file <file>     read message from file
    -s, --sign            annotated and GPG-signed tag
    --cleanup <mode>      how to strip spaces and #comments from message
    -u, --local-user <key id>
                          use another key to sign the tag
    -f, --force           replace the tag if exists
    --column[=<style>]    show tag list in columns
Tag listing options
    --contains <commit>   print only tags that contain the commit
    --points-at <object>  print only tags of the object
[error] java.lang.RuntimeException: Nonzero exit value: 129
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:134)
[error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:104)
[error] 	at Mima$.binaryCompatibilityVersions(Mima.scala:13)
[error] 	at Settings$.$anonfun$mima$1(Settings.scala:161)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit value: 129
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```

**Comment by sbrunk** [comment]
I can't produce locally but I think it could be related to the newly added Migration Manager (the mima sbt plugin).

Could you got to the commit just before mima was added:
```bash
git checkout b854636401ff8ac25b7dfc4bedbb27e8901744cc
```
and try if that works for you?

**Comment by alexarchambault** [comment]
Yes, seems the `--merged` option, used [here](https://github.com/almond-sh/almond/blob/c682feed9eb47d8d61fffaf63927dbff4f946ff3/project/Mima.scala#L13), was added in git `2.7.2`.

@dspautz Would switching to a more recent version of git be an option for you?

**Comment by alexarchambault** [comment]
Closing as stale, we don't use sbt any more
