### ISSUE TITLE
SparkException: Task not serializable

### ISSUE THREAD

**Issue by lemeb** [almond-sh/almond#401]
Take the following code:

```scala
// Jupyter Lab 1.0.4, Java 1.8.0_212, and Scala 2.12.8; on OSX 10.15 beta  
import $ivy.`org.apache.spark::spark-sql:2.4.0` 
import $ivy.`sh.almond::almond-spark:0.6.0`
import org.apache.spark.sql._
val spark = NotebookSparkSession.builder().master("local[*]").getOrCreate()
var sc = spark.sparkContext

// ...
def plusOne(x: Int): Int = { 
  x + 1 
}
sc.parallelize(1 to 10).map(plusOne).collect
```

Here is what it returns:

```scala
org.apache.spark.SparkException: Task not serializable
  org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:403)
  org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:393)
  org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
  org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
  org.apache.spark.rdd.RDD.$anonfun$map$1(RDD.scala:371)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  org.apache.spark.rdd.RDD.map(RDD.scala:370)
  ammonite.$sess.cmd13$Helper.<init>(cmd13.sc:9)
  ammonite.$sess.cmd13$.<init>(cmd13.sc:7)
  ammonite.$sess.cmd13$.<clinit>(cmd13.sc:-1)
java.io.NotSerializableException: almond.api.internal.Modifiable
Serialization stack:
	- object not serializable (class: almond.api.internal.Modifiable, value: almond.api.internal.Modifiable@629a9261)
	- field (class: ammonite.$sess.cmd13$Helper, name: sc$value, type: class almond.api.internal.Modifiable)
	- object (class ammonite.$sess.cmd13$Helper, cmd13)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class ammonite.$sess.cmd13$Helper, functionalInterfaceMethod=scala/runtime/java8/JFunction1$mcII$sp.apply$mcII$sp:(I)I, implementation=invokeStatic ammonite/$sess/cmd13$Helper.$anonfun$res13_2$1:(Lammonite/$sess/cmd13$Helper;I)I, instantiatedMethodType=(I)I, numCaptured=1])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class ammonite.$sess.cmd13$Helper$$Lambda$4315/2030537939, ammonite.$sess.cmd13$Helper$$Lambda$4315/2030537939@3b6d952a)
  org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
  org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
  org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
  org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:400)
  org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:393)
  org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
  org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
  org.apache.spark.rdd.RDD.$anonfun$map$1(RDD.scala:371)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  org.apache.spark.rdd.RDD.map(RDD.scala:370)
  ammonite.$sess.cmd13$Helper.<init>(cmd13.sc:9)
  ammonite.$sess.cmd13$.<init>(cmd13.sc:7)
  ammonite.$sess.cmd13$.<clinit>(cmd13.sc:-1)
```

I highly suspect that this is because the [`api.internal.Modifiable`](../blob/master/modules/scala/scala-kernel-api/src/main/scala/almond/api/internal/Modifiable.scala) Class is not thread-safe, as indicated in the comments. In other words, there is no way around that issue. Am I right?

In any case, thank you for that kick-ass kernel!

PS: The following snippet does work, however:
```scala
sc.parallelize(1 to 10).map(_ + 1).collect
```

PS2: For context, I'm trying to parallelize some Spark jobs, and this is how I stumbled upon this.

**Comment by alexarchambault** [comment]
Nice catch. Seems the internals of the "vars auto-update" don't play well with Java serialization for now…

As a workaround, not relying on `var`s (and possibly `lazy val`s too :| ) should make things work. Alternatively, passing `--auto-update-vars=false ----auto-update-lazy-vals=false` along with `--install` when installing almond should work too (that disables `var`s and `lazy val`s auto-update).

**Comment by cmhh** [comment]
Note sure where else to ask, and this is the closest match I've been able to find.  The following code works for me:

```scala
//Java 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01, scala 2.11.12, on ubuntu 20.04
import $ivy.`org.apache.spark::spark-sql:2.4.0` 
import $ivy.`sh.almond::almond-spark:0.6.0`
import org.apache.spark.sql._
val spark = NotebookSparkSession.builder().master("local[*]").getOrCreate()
var sc = spark.sparkContext
sc.parallelize(1 to 10).map(_ + 1).sum
```

However, when I switch the master from `local[*]` to `spark://172.19.0.4:7077` (a standalone cluster running via docker-compose) this no longer works, and I'm greeted with the following output:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 19 in stage 0.0 failed 4 times, most recent failure: Lost task 19.3 in stage 0.0 (TID 95, 172.19.0.11, executor 1): java.lang.ClassNotFoundException: ammonite.$sess.cmd5$Helper$$anonfun$1
	at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:84)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1986)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ammonite.$sess.cmd5$Helper$$anonfun$1
	at java.lang.ClassLoader.findClass(ClassLoader.java:523)
	at org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:30)
	at org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:79)
	... 33 more

Driver stacktrace:
  org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
  scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
  scala.Option.foreach(Option.scala:257)
  org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
  org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
  org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
  org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  org.apache.spark.rdd.RDD.collect(RDD.scala:944)
  ammonite.$sess.cmd5$Helper.<init>(cmd5.sc:1)
  ammonite.$sess.cmd5$.<init>(cmd5.sc:7)
  ammonite.$sess.cmd5$.<clinit>(cmd5.sc:-1)
java.lang.ClassNotFoundException: ammonite.$sess.cmd5$Helper$$anonfun$1
  org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:84)
  java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  java.lang.Class.forName0(Native Method)
  java.lang.Class.forName(Class.java:348)
  org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
  java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1986)
  java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
  org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
  org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
  org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83)
  org.apache.spark.scheduler.Task.run(Task.scala:121)
  org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
  org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
  org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
java.lang.ClassNotFoundException: ammonite.$sess.cmd5$Helper$$anonfun$1
  java.lang.ClassLoader.findClass(ClassLoader.java:523)
  org.apache.spark.util.ParentClassLoader.findClass(ParentClassLoader.scala:26)
  java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:34)
  java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  org.apache.spark.util.ParentClassLoader.loadClass(ParentClassLoader.scala:30)
  org.apache.spark.repl.ExecutorClassLoader.findClass(ExecutorClassLoader.scala:79)
  java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  java.lang.Class.forName0(Native Method)
  java.lang.Class.forName(Class.java:348)
  org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
  java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1986)
  java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1850)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2160)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2405)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2329)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2187)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
  org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
  org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
  org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:83)
  org.apache.spark.scheduler.Task.run(Task.scala:121)
  org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
  org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
  org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
```

If I start `spark-shell` with `--master spark://172.19.0.4:7077` the code also runs just fine.  

I did make a tiny jar containing the single definition:

```scala
package foo

object bar {
  val f = (x: Int) => x + 1
}
```

and when the jar is added via `interp.load.cp`, the the following does work:

```scala
sc.parallelize(1 to 10).map(foo.bar.f).sum
```

I'm really stumped by this and am hoping I've done something obviously dumb which somebody can point out for me.

**Comment by alexarchambault** [comment]
Closing as stale. [ammonite-spark](https://github.com/almond-sh/ammonite-spark) should have tests specifically for that (that kind of code, against that kind of Spark cluster).
