### ISSUE TITLE
Can't install to in path with space character

### ISSUE THREAD

**Issue by davidcorbin** [almond-sh/almond#485]
```
❯ ./almond --install
Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 47: file:///Users/davidcorbin/Documents/School/COMP 443/almond
	at java.base/java.net.URI$Parser.fail(URI.java:2936)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3107)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3189)
	at java.base/java.net.URI$Parser.parse(URI.java:3137)
	at java.base/java.net.URI.<init>(URI.java:623)
	at almond.kernel.install.Install$.$anonfun$currentAppCommand$1(Install.scala:143)
	at scala.Option.map(Option.scala:242)
	at almond.kernel.install.Install$.currentAppCommand(Install.scala:138)
	at almond.kernel.install.Install$.install(Install.scala:231)
	at almond.kernel.install.Install$.installOrError(Install.scala:280)
	at almond.ScalaKernel$.run(ScalaKernel.scala:46)
	at almond.ScalaKernel$.run(ScalaKernel.scala:15)
	at caseapp.core.app.CaseApp.$anonfun$main$2(CaseApp.scala:68)
	at caseapp.core.app.CaseApp.$anonfun$main$2$adapted(CaseApp.scala:68)
	at scala.util.Either.fold(Either.scala:189)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:68)
	at almond.ScalaKernel.main(ScalaKernel.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

Note that it works when I remove the space in the path.

**Comment by clouds56** [comment]
it's introduced by
https://github.com/almond-sh/almond/blob/56c788d354efa1384d3468e792f4e723c65654c0/modules/shared/kernel/src/main/scala/almond/kernel/install/Install.scala#L141-L143
I wonder why staff like `C:\foo` would fail according to the document

https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html
