### ISSUE TITLE
Kernel installed with default Scala and Almond version throws exception

### ISSUE THREAD

**Issue by janisj** [almond-sh/almond#550]
Installing almond using`SCALA_VERSION=2.12.8 ALMOND_VERSION=0.9.1`  throws exception when starting Jupythers Scala kernel 

```
ERROR ScalaKernel$ Caught exception while initializing interpreter, exiting
almond.amm.AmmInterpreter$PredefException:
  almond.amm.AmmInterpreter$.$anonfun$apply$3(AmmInterpreter.scala:130)
  almond.amm.AmmInterpreter$.$anonfun$apply$3$adapted(AmmInterpreter.scala:125)
  scala.Option$WithFilter.foreach(Option.scala:407)
  almond.amm.AmmInterpreter$.apply(AmmInterpreter.scala:125)
  almond.ScalaInterpreter.ammInterp$lzycompute(ScalaInterpreter.scala:97)
  almond.ScalaInterpreter.ammInterp(ScalaInterpreter.scala:61)
  almond.ScalaKernel$$anon$5.run(ScalaKernel.scala:136)
java.lang.NoSuchMethodError: scala.tools.nsc.classpath.ZipAndJarClassPathFactory$.create(Lscala/reflect/io/AbstractFile;Lscala/tools/nsc/Settings;)Lscala/tools/nsc/util/ClassPath;
  ammonite.interp.ExtraCompilerCompatibility.createZipJarFactory(ExtraCompilerCompatibility.scala:10)
  ammonite.interp.Compiler$.$anonfun$prepareJarCp$2(Compiler.scala:372)
  scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
  scala.collection.Iterator.foreach(Iterator.scala:941)
  scala.collection.Iterator.foreach$(Iterator.scala:941)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
  scala.collection.IterableLike.foreach(IterableLike.scala:74)
  scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  scala.collection.TraversableLike.map(TraversableLike.scala:238)
  scala.collection.TraversableLike.map$(TraversableLike.scala:231)
  scala.collection.AbstractTraversable.map(Traversable.scala:108)
  ammonite.interp.Compiler$.prepareJarCp(Compiler.scala:369)
  ammonite.interp.Compiler$.initGlobalClasspath(Compiler.scala:400)
  ammonite.interp.Compiler$$anon$1.<init>(Compiler.scala:206)
  ammonite.interp.Compiler$.apply(Compiler.scala:141)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:98)
  almond.amm.AmmInterpreter$$anon$1$$anon$2.preprocess(AmmInterpreter.scala:113)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:509)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:569)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:566)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:563)
  scala.Option.getOrElse(Option.scala:189)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:563)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:601)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:397)
  ammonite.util.Catching.flatMap(Res.scala:115)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:388)
  ammonite.util.Res$Success.flatMap(Res.scala:62)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:378)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:126)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:126)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:75)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:32)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
  scala.collection.immutable.List.foldLeft(List.scala:89)
  ammonite.util.Res$.fold(Res.scala:30)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:63)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:128)
  almond.amm.AmmInterpreter$.apply(AmmInterpreter.scala:125)
  almond.ScalaInterpreter.ammInterp$lzycompute(ScalaInterpreter.scala:97)
  almond.ScalaInterpreter.ammInterp(ScalaInterpreter.scala:61)
  almond.ScalaKernel$$anon$5.run(ScalaKernel.scala:136)
```

Scala Kernel started successfully if used `SCALA_VERSION=2.12.8 ALMOND_VERSION=0.8.0`

**Comment by alexarchambault** [comment]
I'm about to update the installation instructions. The following installs almond for scala `2.12.8`:
```bash
$ coursier launch almond:0.9.1 --scala 2.12.8 -- --install
Installed scala kernel under ~/Library/Jupyter/kernels/scala-2.12.8
```
It works fine for me. Can you try installing almond with this command, and see if it works?

**Comment by janisj** [comment]
Installing with this command works fine. Thanks!

**Comment by mushtaq** [comment]
@alexarchambault It does not work on MacOS. I get this error:

```txt
Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 46: file:///Users/mushtaqahmed/Library/Application Support/Coursier/bin/coursier
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at almond.kernel.install.Install$.$anonfun$currentAppCommand$1(Install.scala:143)
	at scala.Option.map(Option.scala:163)
	at almond.kernel.install.Install$.currentAppCommand(Install.scala:138)
	at almond.kernel.install.Install$.install(Install.scala:231)
	at almond.kernel.install.Install$.installOrError(Install.scala:280)
	at almond.ScalaKernel$.run(ScalaKernel.scala:46)
	at almond.ScalaKernel$.run(ScalaKernel.scala:15)
	at caseapp.core.app.CaseApp.$anonfun$main$2(CaseApp.scala:68)
	at caseapp.core.app.CaseApp.$anonfun$main$2$adapted(CaseApp.scala:68)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CaseApp.main(CaseApp.scala:68)
	at almond.ScalaKernel.main(ScalaKernel.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at coursier.cli.launch.Launch$.$anonfun$launch$6(Launch.scala:174)
	at coursier.cli.launch.Launch$.$anonfun$launchCall$11(Launch.scala:329)
	at coursier.cli.launch.Launch$.run(Launch.scala:516)
	at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:116)
	at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:102)
	at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
	at scala.util.Either.fold(Either.scala:191)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
	at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
	at scala.Option.foreach(Option.scala:407)
	at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
	at coursier.cli.Coursier$.main(Coursier.scala:71)
	at coursier.cli.Coursier.main(Coursier.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.Launcher.main(Unknown Source)
```

**Comment by alexarchambault** [comment]
Closing as stale
