### ISSUE TITLE
build.sbt module not found: org.jupyter-scala#scala-kernel_2.12;0.4.2

### ISSUE THREAD

**Issue by virtualdvid** [almond-sh/almond#566]
**Issue**
I'm starting a new project and placed this [line](https://mvnrepository.com/artifact/org.jupyter-scala/scala-kernel_2.12.1/0.4.2) in the `build.sbt` file and I'm getting in the logs:

`module not found: org.jupyter-scala#scala-kernel_2.12;0.4.2`

**build.sbt content**

```
name := "Scala Playground"

version := "1.0"

scalaVersion := "2.12.10"

// https://mvnrepository.com/artifact/org.jupyter-scala/scala-kernel
libraryDependencies += "org.jupyter-scala" %% "scala-kernel" % "0.4.2"
```

**logs**
```
No more data in the client stdin, exiting...
No more data in the server stdin, exiting...
Starting the bsp launcher for bloop...
Opening a bsp server connection with 'bsp --protocol tcp --port 45023'...
Waiting for the bsp connection to come up...
[0m[32m[D][0m Loading workspace settings from bloop.settings.json
[0m[32m[D][0m Waiting for a connection at 127.0.0.1:45023...
The server is listening for incoming connections at tcp://127.0.0.1:45023...
Starting thread that pumps stdin and redirects it to the bsp server...
Starting thread that pumps server stdout and redirects it to the client stdout...
2020.05.15 17:27:22 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at C:\Users\S372277\AppData\Local\scalameta\metals\cache\bsp.trace.json
2020.05.15 17:27:22 INFO  time: connected to build server in 0.63s
2020.05.15 17:27:22 INFO  Connected to Build server v1.4.0-RC1-229-b7c15aa9
2020.05.15 17:27:22 INFO  time: indexed workspace in 0.11s
2020.05.15 17:30:30 INFO  running 'C:\Program Files\Java\jdk1.8.0_131\bin\java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\S372277\AppData\Local\Temp\metals8007540686776396149\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'
2020.05.15 17:30:34 ERROR [INFO] Unable to bind key for unsupported operation: 
2020.05.15 17:30:34 INFO  [info] Loading settings for project scala_playground-build from metals.sbt ...
2020.05.15 17:30:34 INFO  [info] Loading project definition from C:\Users\S372277\damolina\github\scala_playground\project
2020.05.15 17:30:39 INFO  [info] Loading settings for project scala_playground from build.sbt ...
2020.05.15 17:30:39 INFO  [info] Set current project to Scala Playground (in build file:/C:/Users/S372277/damolina/github/scala_playground/)
2020.05.15 17:30:39 INFO  [info] Updating ...
2020.05.15 17:30:41 INFO  [warn] 	module not found: org.jupyter-scala#scala-kernel_2.12;0.4.2
2020.05.15 17:30:41 INFO  [warn] ==== local: tried
2020.05.15 17:30:41 INFO  [warn]   C:\Users\S372277\.ivy2\local\org.jupyter-scala\scala-kernel_2.12\0.4.2\ivys\ivy.xml
2020.05.15 17:30:41 INFO  [warn] ==== public: tried
2020.05.15 17:30:41 INFO  [warn]   https://repo1.maven.org/maven2/org/jupyter-scala/scala-kernel_2.12/0.4.2/scala-kernel_2.12-0.4.2.pom
2020.05.15 17:30:41 INFO  [warn] ==== local-preloaded-ivy: tried
2020.05.15 17:30:41 INFO  [warn]   C:\Users\S372277\.sbt\preloaded\org.jupyter-scala\scala-kernel_2.12\0.4.2\ivys\ivy.xml
2020.05.15 17:30:41 INFO  [warn] ==== local-preloaded: tried
2020.05.15 17:30:41 INFO  [warn]   file:/C:/Users/S372277/.sbt/preloaded/org/jupyter-scala/scala-kernel_2.12/0.4.2/scala-kernel_2.12-0.4.2.pom
2020.05.15 17:30:41 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.05.15 17:30:41 INFO  [warn] 	::          UNRESOLVED DEPENDENCIES         ::
2020.05.15 17:30:41 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.05.15 17:30:41 INFO  [warn] 	:: org.jupyter-scala#scala-kernel_2.12;0.4.2: not found
2020.05.15 17:30:41 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.05.15 17:30:41 INFO  [warn] 
2020.05.15 17:30:41 INFO  [warn] 	Note: Unresolved dependencies path:
2020.05.15 17:30:41 INFO  [warn] 		org.jupyter-scala:scala-kernel_2.12:0.4.2 (C:\Users\S372277\damolina\github\scala_playground\build.sbt#L8-9)
2020.05.15 17:30:41 INFO  [warn] 		  +- scala-playground:scala-playground_2.12:1.0
2020.05.15 17:30:41 INFO  [error] sbt.librarymanagement.ResolveException: unresolved dependency: org.jupyter-scala#scala-kernel_2.12;0.4.2: not found
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
2020.05.15 17:30:41 INFO  [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
2020.05.15 17:30:41 INFO  [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
2020.05.15 17:30:41 INFO  [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
2020.05.15 17:30:41 INFO  [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
2020.05.15 17:30:41 INFO  [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
2020.05.15 17:30:41 INFO  [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
2020.05.15 17:30:41 INFO  [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
2020.05.15 17:30:41 INFO  [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
2020.05.15 17:30:41 INFO  [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
2020.05.15 17:30:41 INFO  [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
2020.05.15 17:30:41 INFO  [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
2020.05.15 17:30:41 INFO  [error] 	at sbt.Execute.work(Execute.scala:278)
2020.05.15 17:30:41 INFO  [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
2020.05.15 17:30:41 INFO  [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020.05.15 17:30:41 INFO  [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020.05.15 17:30:41 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.05.15 17:30:41 INFO  [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020.05.15 17:30:41 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.05.15 17:30:41 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2020.05.15 17:30:41 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2020.05.15 17:30:41 INFO  [error] 	at java.lang.Thread.run(Thread.java:748)
2020.05.15 17:30:41 INFO  [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.jupyter-scala#scala-kernel_2.12;0.4.2: not found
2020.05.15 17:30:41 INFO  [error] Total time: 2 s, completed May 15, 2020 5:30:41 PM
2020.05.15 17:30:41 INFO  build tool exit: 1
2020.05.15 17:30:41 INFO  time: ran 'sbt bloopInstall' in 10s
2020.05.15 17:30:41 ERROR sbt command failed: C:\Program Files\Java\jdk1.8.0_131\bin\java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\S372277\AppData\Local\Temp\metals8007540686776396149\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
2020.05.15 17:30:41 INFO  disconnected: build server
```

How can I install jupyter scala kernel?

I put all this commands in a bat file and got the `scala` kernel but this kernel never started in a notebook:

**bat file**
```
set SCALA_VERSION=2.12.8
set ALMOND_VERSION=0.9.1
mkdir almond
cd almond
bitsadmin /transfer downloadCoursierCli https://git.io/coursier-cli "%cd%\coursier"
bitsadmin /transfer downloadCoursierBat https://git.io/coursier-bat "%cd%\coursier.bat"
.\coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_%SCALA_VERSION%:%ALMOND_VERSION% sh.almond:scala-kernel_%SCALA_VERSION%:%ALMOND_VERSION% -o almond -f && .\almond --install --force
```

got this:
```
DISPLAY: 'downloadCoursierBat' TYPE: DOWNLOAD STATE: TRANS
PRIORITY: NORMAL FILES: 1 / 1 BYTES: 2123 / 2123 (100%)
Unable to complete job - 0x80200002
The requested action is not allowed in the current job sta


C:\Users\S372277\damolina\github\scala_book\almond>.\coursier bootstrap -r jitpack -i user -I user:sh.almond:scala-kernel-api_2.12.8:0.9.1 sh.almond:scala-kernel_2.12.8:0.9.1 -o almond -f   && .\almond --install --force
Wrote C:\Users\S372277\damolina\github\scala_book\almond\almond
Wrote C:\Users\S372277\damolina\github\scala_book\almond\almond.bat
Installed scala kernel under C:\Users\S372277\AppData\Roaming\jupyter\kernels\scala
```

![jupyter scala](https://user-images.githubusercontent.com/33104726/82106275-cb85d400-96d4-11ea-8ba7-578251bf7df9.gif)

**Comment by Krever** [comment]
Hey @virtualdvid, I'm not sure if thats gonna solve you problem but `scala-kernel` artifact is versioned with full scala version (e.g. `2.13.1` instead of `2.13`). You can see available artifacts here: https://mvnrepository.com/artifact/sh.almond/scala-kernel

**Comment by virtualdvid** [comment]
Hi @Krever,

Thank you for your replay, I just tried your suggestion and got the same error:

**build.sbt**
```
name := "Scala Playground"

version := "1.0"

scalaVersion := "2.12.10"

// https://mvnrepository.com/artifact/org.jupyter-scala/scala-kernel
// libraryDependencies += "org.jupyter-scala" %% "scala-kernel" % "0.4.2"

// https://mvnrepository.com/artifact/sh.almond/scala-kernel
libraryDependencies += "sh.almond" %% "scala-kernel" % "0.9.1"

libraryDependencies += "org.scalactic" %% "scalactic" % "3.1.2"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.1.2" % "test"
```


**logs**
```
2020.06.17 09:16:49 INFO  [warn] 	module not found: sh.almond#scala-kernel_2.12;0.9.1
2020.06.17 09:16:49 INFO  [warn] ==== local: tried
2020.06.17 09:16:49 INFO  [warn]   C:\Users\S372277\.ivy2\local\sh.almond\scala-kernel_2.12\0.9.1\ivys\ivy.xml
2020.06.17 09:16:49 INFO  [warn] ==== public: tried
2020.06.17 09:16:49 INFO  [warn]   https://repo1.maven.org/maven2/sh/almond/scala-kernel_2.12/0.9.1/scala-kernel_2.12-0.9.1.pom
2020.06.17 09:16:49 INFO  [warn] ==== local-preloaded-ivy: tried
2020.06.17 09:16:49 INFO  [warn]   C:\Users\S372277\.sbt\preloaded\sh.almond\scala-kernel_2.12\0.9.1\ivys\ivy.xml
2020.06.17 09:16:49 INFO  [warn] ==== local-preloaded: tried
2020.06.17 09:16:49 INFO  [warn]   file:/C:/Users/S372277/.sbt/preloaded/sh/almond/scala-kernel_2.12/0.9.1/scala-kernel_2.12-0.9.1.pom
2020.06.17 09:16:49 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.06.17 09:16:49 INFO  [warn] 	::          UNRESOLVED DEPENDENCIES         ::
2020.06.17 09:16:49 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.06.17 09:16:49 INFO  [warn] 	:: sh.almond#scala-kernel_2.12;0.9.1: not found
2020.06.17 09:16:49 INFO  [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
2020.06.17 09:16:49 INFO  [warn] 
2020.06.17 09:16:49 INFO  [warn] 	Note: Unresolved dependencies path:
2020.06.17 09:16:49 INFO  [warn] 		sh.almond:scala-kernel_2.12:0.9.1 (C:\Users\S372277\damolina\github\scala_playground\build.sbt#L11-12)
2020.06.17 09:16:49 INFO  [warn] 		  +- scala-playground:scala-playground_2.12:1.0
2020.06.17 09:16:51 INFO  [error] sbt.librarymanagement.ResolveException: unresolved dependency: sh.almond#scala-kernel_2.12;0.9.1: not found
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Using$.apply(Using.scala:9)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
2020.06.17 09:16:51 INFO  [error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
2020.06.17 09:16:51 INFO  [error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
2020.06.17 09:16:51 INFO  [error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
2020.06.17 09:16:51 INFO  [error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
2020.06.17 09:16:51 INFO  [error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
2020.06.17 09:16:51 INFO  [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
2020.06.17 09:16:51 INFO  [error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
2020.06.17 09:16:51 INFO  [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
2020.06.17 09:16:51 INFO  [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
2020.06.17 09:16:51 INFO  [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
2020.06.17 09:16:51 INFO  [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
2020.06.17 09:16:51 INFO  [error] 	at sbt.Execute.work(Execute.scala:278)
2020.06.17 09:16:51 INFO  [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
2020.06.17 09:16:51 INFO  [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020.06.17 09:16:51 INFO  [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020.06.17 09:16:51 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.06.17 09:16:51 INFO  [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020.06.17 09:16:51 INFO  [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.06.17 09:16:51 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2020.06.17 09:16:51 INFO  [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2020.06.17 09:16:51 INFO  [error] 	at java.lang.Thread.run(Thread.java:748)
2020.06.17 09:16:51 INFO  [error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: sh.almond#scala-kernel_2.12;0.9.1: not found
2020.06.17 09:16:51 INFO  [error] Total time: 4 s, completed Jun 17, 2020 9:16:51 AM
2020.06.17 09:16:51 INFO  build tool exit: 1
2020.06.17 09:16:51 INFO  time: ran 'sbt bloopInstall' in 25s
2020.06.17 09:16:51 ERROR sbt command failed: C:\Program Files\Java\jdk1.8.0_131\bin\java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar C:\Users\S372277\AppData\Local\Temp\metals6385989529185648651\sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall
2020.06.17 09:16:51 INFO  disconnected: build server
```

**Comment by Krever** [comment]
@virtualdvid You're still trying to use `sh.almond#scala-kernel_2.12;0.9.1` whereas the correct one is `sh.almond#scala-kernel_2.12.10;0.9.1`. The easiest way to use it is:
```
libraryDependencies += "sh.almond" % "scala-kernel_2.12.10" % "0.9.1"
```
This should work, but I haven't tested it.

**Comment by virtualdvid** [comment]
mmm this is interesting. I tried what you said and `sbt` by default is adding the version to scala_kernel_<version>. 

```
// https://mvnrepository.com/artifact/sh.almond/scala-kernel
libraryDependencies += "sh.almond" % "scala-kernel_2.12.10" % "0.9.1"
```

and got this:
`[warn] 	module not found: sh.almond#scala-kernel_2.12.10_2.12;0.9.1`

**Comment by virtualdvid** [comment]
It worked! I'm new with `scala` and happy to learn something today about the `%%` and `%` to add the version automatically or manual in the `build.sbt`. Thanks!

**Comment by virtualdvid** [comment]
Thanks @alexarchambault  good to know that one too! I got some errors with:
```
libraryDependencies += "sh.almond" % "scala-kernel_2.12.10" % "0.9.1"
```
```
[warn] 	module not found: com.github.jupyter#jvm-repr;0.4.0
```
I tried:
```
// https://mvnrepository.com/artifact/org.jupyter-scala/scala-kernel
libraryDependencies += "org.jupyter-scala" % "scala-kernel_2.12.1" % "0.4.2"
```
and it worked with not issues. Wondering how to launch the notebook. My background is in `python` and I'm use to `jupyter notebook` command. Do you know the equivalent for sbt? I'm reading here the documentation to figure it out. Thanks!

**Comment by alexarchambault** [comment]
Closing as stale
