### ISSUE TITLE
sbt jupyterStart shell failed

### ISSUE THREAD

**Issue by icankeep** [almond-sh/almond#790]
hello, I try to compile the project refer to this [document](https://almond.sh/docs/dev-from-sources)

```bash
git clone https://github.com/almond-sh/almond.git
cd almond
sbt jupyterStart shell 
```

but it failed, I searched a lot of blogs but still didn't solve it. The error message is as follows:

```bash
$ sbt jupyterStart shell         
[info] welcome to sbt 1.4.2 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from /Users/foo/.sbt/1.0/plugins
[info] loading settings for project almond-build from plugins.sbt ...
[info] loading project definition from /Users/foo/work/code/almond/project
sbt.internal.IncompatiblePluginsException: Binary incompatibility in plugins detected.
        at sbt.internal.PluginDiscovery$.incompatiblePlugins(PluginDiscovery.scala:184)
        at sbt.internal.PluginDiscovery$.loadModules(PluginDiscovery.scala:168)
        at sbt.internal.PluginDiscovery$.binarySourceModules(PluginDiscovery.scala:153)
        at sbt.internal.PluginDiscovery$.discover$1(PluginDiscovery.scala:43)
        at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:57)
        at sbt.internal.Load$.loadPlugins(Load.scala:1305)
        at sbt.internal.Load$.loadPluginDefinition(Load.scala:1250)
        at sbt.internal.Load$.buildPlugins(Load.scala:1229)
        at sbt.internal.Load$.plugins(Load.scala:1208)
        at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
        at sbt.internal.Load$.timed(Load.scala:1382)
        at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
        at sbt.internal.Load$.timed(Load.scala:1382)
        at sbt.internal.Load$.loadUnit(Load.scala:688)
        at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:486)
        at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:180)
        at sbt.internal.BuildLoader.apply(BuildLoader.scala:245)
        at sbt.internal.Load$.loadURI$1(Load.scala:548)
        at sbt.internal.Load$.loadAll(Load.scala:564)
        at sbt.internal.Load$.loadURI(Load.scala:494)
        at sbt.internal.Load$.load(Load.scala:473)
        at sbt.internal.Load$.$anonfun$apply$1(Load.scala:242)
        at sbt.internal.Load$.timed(Load.scala:1382)
        at sbt.internal.Load$.apply(Load.scala:242)
        at sbt.internal.Load$.defaultLoad(Load.scala:55)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:929)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:929)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:882)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:271)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:162)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:162)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:162)
        at sbt.MainLoop$.run(MainLoop.scala:143)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:118)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:111)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:65)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:50)
        at sbt.MainLoop$.runLogged(MainLoop.scala:41)
        at sbt.StandardMain$.runManaged(Main.scala:188)
        at sbt.xMain$.$anonfun$run$6(Main.scala:100)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:552)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:542)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:542)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
        at sbt.xMain$.run(Main.scala:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:120)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.NoClassDefFoundError: wvlet/log/LogSupport
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:24)
        at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:32)
        at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:37)
        at scala.collection.immutable.Stream.map(Stream.scala:418)
        at sbt.internal.inc.ModuleUtilities$.getCheckedObjects(ModuleUtilities.scala:37)
        at sbt.internal.PluginDiscovery$.loadModules(PluginDiscovery.scala:163)
        ... 75 more
Caused by: java.lang.ClassNotFoundException: wvlet.log.LogSupport
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 94 more
[error] sbt.internal.IncompatiblePluginsException: Binary incompatibility in plugins detected.
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

```

**Comment by alexarchambault** [comment]
Closing as stale, we're not using sbt anymore
