### ISSUE TITLE
Kernel error : WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by rsrini7** [almond-sh/almond#80]
I am getting below error when accessing scala from jupyter.
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, _args, *_kwargs))
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "C:\Python27\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "C:\Python27\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "C:\Python27\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Python27\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "C:\Python27\lib\site-packages\tornado\gen.py", line 282, in wrapper
    yielded = next(result)
  File "C:\Python27\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(__kwargs)
  File "C:\Python27\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(__kwargs)
  File "C:\Python27\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    *_kw)
  File "C:\Python27\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, *_kw)
  File "C:\Python27\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, *_kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

**Comment by alexarchambault** [comment]
Closing, that issue's about a quite old version
