### ISSUE TITLE
Unrecognized cpu architecture (x86)

### ISSUE THREAD

**Issue by stevenhurwitt** [almond-sh/almond#879]
I'm trying to install almond scala kernel on Windows 11. When I run this command: 

```.\coursier launch --fork almond:0.11.1 -- --scala 2.12.15 --install```

I get the error:

```
Exception in thread "main" java.lang.Exception: Unrecognized CPU architecture: x86
        at coursier.jvm.JvmIndex$.defaultArchitecture(JvmIndex.scala:205)
        at coursier.jvm.JvmCache$.apply(JvmCache.scala:24)
        at coursier.cli.jvm.SharedJavaParams.jvmCacheOf$1(SharedJavaParams.scala:32)
        at coursier.cli.jvm.SharedJavaParams.cacheAndHome(SharedJavaParams.scala:40)
        at coursier.cli.launch.LaunchParams.$anonfun$javaPath$3(LaunchParams.scala:31)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Did i accidentally install the 32 bit version of java or scala or something? My architecture should be x64, but i'm not sure what it's saying is x86.

Here are the versions of java, scala, etc:

```
java version "1.8.0_301"
```

```
Scala code runner version 2.12.15 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.
```

```
sbt version in this project: 1.5.0
sbt script version: 1.5.0
```

**Comment by victor1234544** [comment]
Did you solve this problem?

**Comment by alexarchambault** [comment]
> Did i accidentally install the 32 bit version of java or scala or something?

Possibly a 32 bit JVM, yes, given the architecture it gives.
