### ISSUE TITLE
Jupyter console crashing

### ISSUE THREAD

**Issue by borice** [almond-sh/almond#98]
I installed the latest release of jupyter-scala (following the README). Then, I launched `jupyter console --kernel scala211` and typed `(1 to 10)` at the prompt. After getting the warning, I pressed ENTER at the `In [2]:` prompt. Here's what happened: 

Any ideas?

```
$ jupyter console --kernel scala211
Jupyter console 5.0.0

Jupyter Scala 0.3.0-M3 (Ammonium 0.4.0-M6-1) (Scala 2.11.8)
Initial dependencies:
  com.github.alexarchambault.jupyter:scala-api_2.11.8:0.3.0-M3:compile
  org.scala-lang:scala-compiler:2.11.8:macro



In [1]: (1 to 10)/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py:571: UserWarning: The kernel did not respond t.
  warn('The kernel did not respond to an is_complete_request. '
In [1]: (1 to 10)
res0: collection.immutable.Range.Inclusive = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [2]:
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/app.py", line 151, in start
    self.shell.mainloop()
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 463, in mainloop
    self.interact()
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 448, in interact
    code = self.prompt_for_code()
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 408, in prompt_for_code
    reset_current_buffer=True)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 389, in run
    self.eventloop.run(self.input, self.create_eventloop_callbacks())
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 153, in run
    t()
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/eventloop/posix.py", line 81, in read_from_stdin
    inputstream.feed(data)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 390, in feed
    self._input_parser.send(c)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 299, in _input_parser_generator
    self._call_handler(match, prefix)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/terminal/vt100_input.py", line 332, in _call_handler
    self.feed_key_callback(KeyPress(key, insert_text))
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 1019, in feed_key
    cli.input_processor.process_keys()
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 201, in process_keys
    self._process_coroutine.send(key_press)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 158, in _process
    self._call_handler(matches[-1], key_sequence=buffer)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/key_binding/input_processor.py", line 228, in _call_handler
    handler.call(event)
  File "/usr/local/lib/python3.5/site-packages/prompt_toolkit/key_binding/registry.py", line 31, in call
    return self.handler(event)
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 342, in _
    more, indent = self.check_complete(d.text)
  File "/usr/local/lib/python3.5/site-packages/jupyter_console/ptshell.py", line 426, in check_complete
    more = (code.splitlines()[-1] != "")
IndexError: list index out of range
```

Environment:

```
$ python3 --version
Python 3.5.2
$ java -version
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
$ ipython --version
5.1.0
$ jupyter --version
4.1.1
$ cat ~/Library/Jupyter/kernels/scala211/kernel.json
{
  "language" : "scala211",
  "display_name" : "Scala 2.11",
  "argv" : [
    "java",
    "-noverify",
    "-jar",
    "/Users/capitanu/Library/Jupyter/kernels/scala211/launcher.jar",
    "launch",
    "com.github.alexarchambault.jupyter:scala-cli_2.11.8:0.3.0-M3",
    "-r",
    "https://dl.bintray.com/scalaz/releases",
    "-I",
    "jupyter-scala-compile:com.github.alexarchambault.jupyter:scala-api_2.11.8:0.3.0-M3",
    "-I",
    "jupyter-scala-macro:org.scala-lang:scala-compiler:2.11.8",
    "-i",
    "jupyter-scala-compile,jupyter-scala-macro",
    "-M",
    "jupyter.scala.JupyterScala",
    "-V",
    "org.scala-lang:scala-library:2.11.8",
    "-V",
    "org.scala-lang:scala-compiler:2.11.8",
    "-V",
    "org.scala-lang:scala-reflect:2.11.8",
    "--",
    "--quiet",
    "--connection-file",
    "{connection_file}"
  ]
}
```

**Comment by alexarchambault** [comment]
This seems fine with the current master (and all releases under the name "almond" should be fine too).
